{
 "title": "PerfReactorDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total"
    }
   ]
  },
  {
   "title": "Web Flux - Web Flux Avec Delai",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/flux/delay\"}"
    }
   ]
  },
  {
   "title": "Spring MVC Server Threads State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"spring-mvc-server:8082\",job=\"spring-boot-app\",state=~\".*\"}"
    }
   ]
  },
  {
   "title": "Spring Web Flux- RSocket Avec delai",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/rsocket/delay/{name}\"}"
    }
   ]
  },
  {
   "title": "RSocket Client Threads State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"rsocket-client:8081\",job=\"spring-boot-app\",state=~\".*\"}"
    }
   ]
  },
  {
   "title": "Web Flux RSocket Call - Retrieve Text Flux ",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/hello/{name}\"}"
    }
   ]
  },
  {
   "title": "RSocket Server Threads State",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{instance=\"rsocket-server:8080\",job=\"spring-boot-app\",state=~\".*\"}"
    }
   ]
  },
  {
   "title": "Erreur HTTP",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 30 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{exception=~\".*\",instance=~\".*\",job=\"spring-boot-app\",method=\"GET\",outcome=\"SERVER_ERROR\",status=\"500\",uri=~\".*\"}"
    }
   ]
  }
 ]
}