{
 "title": "ThroughPut and Latency",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/rsocket/delay/{name}\"}[10s])"
    }
   ]
  },
  {
   "title": "Throughput Without RSocket",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/flux/delay\"}[10s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/rsocket/delay/{name}\"}[10s])/rate(http_server_requests_seconds_count{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/rsocket/delay/{name}\"}[10s])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Withour RSocket ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/flux/delay\"}[10s])/rate(http_server_requests_seconds_count{exception=\"None\",instance=\"rsocket-client:8081\",job=\"spring-boot-app\",method=\"GET\",outcome=\"UNKNOWN\",status=\"200\",uri=\"/flux/flux/delay\"}[10s])"
    }
   ]
  }
 ]
}